### ISSUE TITLE
Set custom position

### ISSUE THREAD

**Issue by sinanku** [JSSAlertView/JSSAlertView#38]
Would be nice to enable setting a custom position for JSSAlertView (e.g. a value that either adds or subtracts from height position), reason being when a keyboard is visible on the screen it does not appear centered (even though it is absolute positioned in the center).  Thanks for the awesome work!

**Comment by syky27** [comment]
Hi, I will have look at this during weekend, and I will probably implement it...

**Comment by sinanulkuatam** [comment]
Awesome, thank you!

**Comment by syky27** [comment]
@sinanku Do you still need this?

**Comment by sinanku** [comment]
@syky27 no longer necessary, thanks!
