### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by tiferrei** [JSSAlertView/JSSAlertView#43]
With the new Swift 3 this framework has about 70 errors. I have analysed it and they are mostly just syntax changes, I would be happy to update it and then do a pull request, however, there is use of `CGRectMake` which is no longer available in Swift.

**Comment by MaeseppTarvo** [comment]
At first I had about 93 errors, I didn't do anything and now I have only 4 of them. Two "Missing argument label 'of:' in call" and one "Cannot convert value of type '[String : UIFont?]' to expected argument type '[String : AnyObject]?'" Tried to fix those and got some weird error says that {bracked needed after if condition even if it is there.

**Comment by tiferrei** [comment]
Probably yo selected JSSAlertView's framework when converting to swift3, it did what he could, but not everything, also because swift 3 removes `CGRectMake`, but (at least if you're using CocoaPods or Carthage) because if you need to install it again it will still be in swift 2.

**Comment by syky27** [comment]
Hi, guys, thank you for your effort. I will have look at it on weekend.

There are several things that needs to be rewritten I might swipe those with swift3 conversion.

**Comment by tiferrei** [comment]
Alright @syky27, when you start can you please go slowly add the changes to a separate branch called `swift3` or something like that? It would be quite handy to be able to take a look at some of the changes. Thanks!

**Comment by syky27** [comment]
Sure.

**Comment by syky27** [comment]
Hi, for now you can copypaste code in branch swift3 until I resolve #52

**Comment by HaciKale** [comment]
Hey Guys!
it's not really working with swift 3, am I getting the wrong code or something??

**Comment by syky27** [comment]
Use the code in swift branch and copy paste it to your project. 

There is some problem with cocoapod

**Comment by HaciKale** [comment]
perfect, thanks! now it works! It's really nice! just have to change the code a bit so I can add more than 1 button and it's good 👍

**Comment by syky27** [comment]
New version of pod released 🎉 supporting swift 3
