### ISSUE TITLE
Programmatically Dismiss View

### ISSUE THREAD

**Issue by zcanter** [JSSAlertView/JSSAlertView#48]
Hello. Great job on this framework!

Is there a way to programmatically dismiss the JSAlertView? I am trying to have it dismiss from a shake gesture.

Thank you.

**Comment by zcanter** [comment]
Was able to solve this on my by adding this to the JSAlertView class:

// Check for shake gesture, vibrate, then remove alert view    

override public func motionEnded(motion: UIEventSubtype, withEvent event: UIEvent?) {
        if(event!.subtype == UIEventSubtype.MotionShake) {
            closeView(true, source: .Close);
        }
    }

**Comment by syky27** [comment]
This is partial solution, because if I implement this it will be active always even for those who do not want to have this functionality in their app.

**Comment by syky27** [comment]
I will do it as soon as I will find a time for it.

**Comment by syky27** [comment]
You can always implement your solution inside the viewcontroller JSSAlertView is called from.

Keeping it like this.

**Comment by oleynikd** [comment]
Why `closeView` method isn't public?

**Comment by syky27** [comment]
Good question.

It was not intended to be used in the first iteration.

I actually do not see any reason why it should not be public now.

**Comment by oleynikd** [comment]
Thanks, for fast response! That would be great!
