### ISSUE TITLE
Crash on iOS10 Xcode 8 - Swift 3

### ISSUE THREAD

**Issue by alissonbarauna** [JSSAlertView/JSSAlertView#49]
Hey,

After update my Xcode, and using Swift 3, I'm having a crash on showing JSSAlrtView.
Can you please help me on that?
I really love your framework, and would be so sad stop using that due this issue :/
The problem seems to be related to the "text" parameter. The crash only happens when I add this parameter to the "show" method. All other parameters seems to be working fine.

Ps.: I tried to debug, but it crashes on the part Xcode shows Assembly code. I'm not advanced on programming, then I'm not able to figure the problem out.
And plus, the icon on Swift 3 keeps aligned to the left, not in the center.

There is an image attached, showing the alert working without text, and the image aligned to the left.

If you guys need any info else, please let me know.

Thanks a lot in advance.

```
2016-09-08 19:43:47.896 Gplayces[6195:1609467] -[_SwiftValue pointSize]: unrecognized selector sent to instance 0x7d074570
2016-09-08 19:43:47.904 Gplayces[6195:1609467] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_SwiftValue pointSize]: unrecognized selector sent to instance 0x7d074570'
*** First throw call stack:
(
	0   CoreFoundation                      0x0168a212 __exceptionPreprocess + 194
	1   libobjc.A.dylib                     0x009ffe66 objc_exception_throw + 52
	2   CoreFoundation                      0x017033dc -[NSObject(NSObject) doesNotRecognizeSelector:] + 172
	3   CoreFoundation                      0x0160934c ___forwarding___ + 1052
	4   CoreFoundation                      0x01608f0e _CF_forwarding_prep_0 + 14
	5   UIFoundation                        0x0b691087 __NSStringDrawingEngine + 4090
	6   UIFoundation                        0x0b69005f -[NSString(NSExtendedStringDrawing) boundingRectWithSize:options:attributes:context:] + 188
	7   Gplayces                            0x000ad487 _TFC8Gplayces12JSSAlertView21viewDidLayoutSubviewsfT_T_ + 7447
	8   Gplayces                            0x000aee62 _TToFC8Gplayces12JSSAlertView21viewDidLayoutSubviewsfT_T_ + 34
	9   UIKit                               0x024ac811 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1598
	10  libobjc.A.dylib                     0x00a151b9 -[NSObject performSelector:withObject:] + 59
	11  QuartzCore                          0x02261769 -[CALayer layoutSublayers] + 141
	12  QuartzCore                          0x02254a47 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	13  QuartzCore                          0x0225489d _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 21
	14  QuartzCore                          0x021de49f _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 339
	15  QuartzCore                          0x0220d290 _ZN2CA11Transaction6commitEv + 498
	16  QuartzCore                          0x0220eda0 _ZN2CA11Transaction17flush_transactionEv + 38
	17  UIKit                               0x0240685c _afterCACommitHandler + 375
	18  CoreFoundation                      0x0162976e __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 30
	19  CoreFoundation                      0x016296c7 __CFRunLoopDoObservers + 391
	20  CoreFoundation                      0x0160d3a6 __CFRunLoopRun + 1414
	21  CoreFoundation                      0x0160cbab CFRunLoopRunSpecific + 395
	22  CoreFoundation                      0x0160ca0b CFRunLoopRunInMode + 123
	23  GraphicsServices                    0x063c6b4c GSEventRunModal + 177
	24  GraphicsServices                    0x063c69c7 GSEventRun + 80
	25  UIKit                               0x023d77fb UIApplicationMain + 148
	26  Gplayces                            0x00064ee1 main + 145
	27  libdyld.dylib                       0x04d78799 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

![simulator screen shot 8 sep 2016 20 56 42](https://cloud.githubusercontent.com/assets/19950837/18370874/c77ea71c-7606-11e6-80e9-f95352a4da10.png)

**Comment by syky27** [comment]
I will have a look at it

**Comment by alissonbarauna** [comment]
Oh, I would be so grateful.
Thanks in advance Tomas.

If you need any information, please let me know.

**Comment by alissonbarauna** [comment]
Hey Tomas!

Do you have any updates concerning this issue?

Thanks a lot in advance.

**Comment by alissonbarauna** [comment]
Tomas, I think I figured out the problem.

I changed the textAttr variable to a "example" [NSFontAttributeName: UIFont(name:"Arial", size:14.0)!, NSForegroundColorAttributeName:UIColor.black] and it worked.
It seems Swift is not able to read font attributes from UITextView.

Using fixed attributes works fine.

![screenshot at sep 13 23-13-46](https://cloud.githubusercontent.com/assets/19950837/18497780/c1bf5a10-7a07-11e6-9ed7-016be03bd493.png)

**Comment by syky27** [comment]
Hi

I will have a look at it right away.

**Comment by syky27** [comment]
Hi, I gave it good 3 hours did not get it working, I will continue tomorrow. 

If you know how to convert the pod to working version with swift3 with backward compatibility feel free to contribute.

**Comment by RichardBoyder** [comment]
anyone managed to fix this for swift 3?

**Comment by syky27** [comment]
not yet
--
Tomas Sykora

**Comment by RichardBoyder** [comment]
cool. I wish i had enough knowledge to help but not yet. By the way, this is a awesome plugin. Love the popup. Many thanks for sharing with us all.

**Comment by alissonbarauna** [comment]
I have fixed the crash on Swift 3, but I don't use Pods (and don't have knowledge on that).
If you guys want, I can send you the class I'm using to use the workaround.

Thanks.

**Comment by tiferrei** [comment]
@alissonbarauna that would be awesome!! If you can please send it to me and I'll take care of pull requests and cocoa pods.

**Comment by RichardBoyder** [comment]
any lucky updating pods to swift 3? @tiferrei

**Comment by tiferrei** [comment]
Hello there @RichardBoyder, it seems to be a success! I am currently testing it with all the functions available, but for now everything seems to be working! You can take a look at how things are going in my [fork](https://github.com/tiferrei/JSSAlertView).

**Comment by mat0pad** [comment]
@syky27 to correct the issue and to avoid using static fonts please make the following changes 
`// position the title
        let titleString = titleLabel.text! as NSString
        let titleAttr = [NSFontAttributeName:titleLabel.font!] as [String: Any] // UPDATED
        let titleSize = CGSize(width: contentWidth, height: 90)
        let titleRect = titleString.boundingRect(with: titleSize, options: NSStringDrawingOptions.usesLineFragmentOrigin, attributes: titleAttr, context: nil)
        yPos += padding
        self.titleLabel.frame = CGRect(x: self.padding, y: yPos, width: self.alertWidth - (self.padding*2), height: ceil(titleRect.size.height))
        yPos += ceil(titleRect.size.height)
        
        
        // position text
        if self.textView != nil {
            let textString = textView.text!
            let textAttr = [NSFontAttributeName: textView.font!] as [String: Any] // UPDATED
            let realSize = textView.sizeThatFits(CGSize(width: contentWidth, height: CGFloat.greatestFiniteMagnitude))
            let textSize = CGSize(width: contentWidth, height: CGFloat(fmaxf(Float(90.0), Float(realSize.height))))
            let textRect = textString.boundingRect(with: textSize, options: NSStringDrawingOptions.usesLineFragmentOrigin, attributes: textAttr, context: nil)
            self.textView.frame = CGRect(x: self.padding, y: yPos, width: self.alertWidth - (self.padding*2), height: ceil(textRect.size.height)*2)
            yPos += ceil(textRect.size.height) + padding/2
        }
`

**Comment by tiferrei** [comment]
Thanks @mat0pad, will update that on my code and submit a PR

**Comment by syky27** [comment]
Hi, for now you can copypaste code in branch swift3 until I resolve #52

**Comment by syky27** [comment]
👌New version of JSSAlertView 3.0.0 supporting swift 3 just got released yaaaayy... 🎉

**Comment by syky27** [comment]
Sorry it took so much time, I was trying to do it using cocoapod prerelease version which supported this but, without any luck until now, when I read on Twitter that new stable version od cocoapods supporting this was released....

So Thank you for your patience....
