### ISSUE TITLE
Example isn't working in Swift 3.0

### ISSUE THREAD

**Issue by hdinhof1** [JSSAlertView/JSSAlertView#55]
Demo app isn't compatible with the current Xcode 8.1 environment. Tried fixing the pod versions "pod 'Quick', '~> 0.8'"   to pod 'Quick'

Then did a pod update but its not working. Alas no quick fix here.

**Comment by syky27** [comment]
Hi, I just ran `pod try JSSAlertView` using `Xcode Version 8.1 (8B62)`

And it works like a charm.

**Comment by hdinhof1** [comment]
I am using Xcode Version 8.1.

The problem stems from the Quick framework. I'm getting compiler errors (on
closure method definitions).

**Comment by syky27** [comment]
Well I am not...
It works just fine for me, you will have to be more specific.


On Wed, Nov 2, 2016 at 3:37 PM, Henry Dinhofer <notifications@github.com> wrote:
I am using Xcode Version 8.1.

The problem stems from the Quick framework. I'm getting compiler errors (on
closure method definitions).
