### ISSUE TITLE
Swift 3 version

### ISSUE THREAD

**Issue by spiking** [JSSAlertView/JSSAlertView#59]
Hi!

How do you update to the version compatible with Swift 3? With pod 'JSSAlertView' the 1.1.5 version is installed, which generates 74 issues. I tried updating and reinstalling the pods but it made no difference.

Is the updated version not in the master branch?

Thanks!

**Comment by syky27** [comment]
Did you try `pod update` ? What is output of that and how does your Podfile look like?

**Comment by spiking** [comment]
Yes, I tried pod update. I am using Xcode 8.1, MacOS Sierra 10.12.1

Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
... (other pods)
**Using JSSAlertView (1.1.5)**
Generating Pods project
[1]    2173 abort      pod update

In the podfile I have 

target 'AppName' Do
use_frameworks!
... (other pods)
pod 'JSSAlertView'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

**Comment by syky27** [comment]
Ok, weird I just tried it with this result

```
╭─syky at aluminium in ~ using  ‹2.2.4› 16-11-11 - 15:29:34
╰─○ cd Desktop/test
╭─syky at aluminium in ~/Desktop/test using  ‹2.2.4› 16-11-11 - 15:29:37
╰─○ pod init
╭─syky at aluminium in ~/Desktop/test using  ‹2.2.4› 16-11-11 - 15:29:39
╰─○ vim Podfile
╭─syky at aluminium in ~/Desktop/test using  ‹2.2.4› 16-11-11 - 15:29:52
╰─○
╭─syky at aluminium in ~/Desktop/test using  ‹2.2.4› 16-11-11 - 15:29:53
╰─○
╭─syky at aluminium in ~/Desktop/test using  ‹2.2.4› 16-11-11 - 15:29:54
╰─○
╭─syky at aluminium in ~/Desktop/test using  ‹2.2.4› 16-11-11 - 15:29:54
╰─○ pod install
Analyzing dependencies
Downloading dependencies
Installing JSSAlertView (3.0.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `test.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
╭─syky at aluminium in ~/Desktop/test using  ‹2.2.4› 16-11-11 - 15:29:57
╰─○ cat Podfile
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'JSSAlertView'
  # Pods for test

end
╭─syky at aluminium in ~/Desktop/test using  ‹2.2.4› 16-11-11 - 15:30:15
╰─○
```

So it works for me

**Comment by syky27** [comment]
What is your cocoapods version?

**Comment by spiking** [comment]
That is weird indeed. I can try to update it, see if it solves the problem.

**Comment by spiking** [comment]
Thanks! It seems like it resolved the issue by updating cocoapods!

**Comment by syky27** [comment]
Happy coding
--
Tomas Sykora
