### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Uskinn** [JSSAlertView/JSSAlertView#67]
Hi,
Just installed the pod 'JSSAlertView' for Swift 3, have 72 errors. Is any way to install it without any errors?
Thank you.

**Comment by syky27** [comment]
Can you show me what kind of errors, this doesn't happen to me.

Thanks

**Comment by Uskinn** [comment]
syky27,

Thank you for the quick response.

I reinstalled the pod and cleaned the project about five times. Now everything works great! 
It was something. 

P.S.
Sorry that bothered you without real issue.

**Comment by syky27** [comment]
No Worries.
