### ISSUE TITLE
removeFromParent

### ISSUE THREAD

**Issue by RichardBoyder** [JSSAlertView/JSSAlertView#80]
I have updated to swift 4.2 and updated the pod file. however i am getting this error:
removeFromParent()' has been renamed to 'removeFromParentViewController()'

Has this been fixed for the latest swift?

**Comment by RichardBoyder** [comment]
There are other issues as well. And i removed from pod file , and re added to make sure i have latest.

**Comment by syky27** [comment]
Hi @RichardBoyder 

`removeFromParentViewController()` has been renamed to `removeFromParent()` in `swift4.2`
`removeFromParentViewController()` was obsoleted in Swift 4.2

I suspect that you are not building your project with swift4.2 and that is the reason why you are getting this error.

Could you make sure, that you are using swift 4.2 on you project?

**Comment by syky27** [comment]
As you can see, here was the same problem: https://github.com/zhangao0086/DKImagePickerController/issues/508
